server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.xianshuiyu.webshop.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/11111
    username: root
    password: Xem212121
  cors:
    allowed-origins:
      - "http://localhost:8080"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true # 是否允许发送身份凭证（如 cookies）
    max-age: 3600 # 预检请求的缓存时间（单位：秒）